name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allow manual triggering
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install flit
          flit install

      - name: Test with pytest
        run: pytest -v

      - name: Check type annotations
        run: |
          mypy --non-interactive .

      - name: Check data prep scripts still work
        run: |
          # Copy to temp location
          mkdir -p ../tmp/stringcalc
          cp -vr data ../tmp/stringcalc/
          cp -vr stringcalc ../tmp/stringcalc/

          # Run scripts
          cd ../tmp/stringcalc/data
          for f in *.py; do
            if [ $f == "daddario_extract.py" ]; then continue; fi
            python $f
          done

          # Compare results to those in the repo
          cd ../stringcalc/data
          rc=0
          for f in *.csv; do
            echo $f
            cmp $f $GITHUB_WORKSPACE/stringcalc/data/$f || rc=$?
          done
          exit $rc

  panel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        stringcalc: ["local", "pypi"]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (micromamba)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: panel/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Install stringcalc (${{ matrix.stringcalc }})
        run: |
          if [ "${{ matrix.stringcalc }}" == "local" ]; then
            pip install -e . --no-deps
          elif [ "${{ matrix.stringcalc }}" == "pypi" ]; then
            pip install stringcalc
          else
            exit 1
          fi

      - name: Run the app script
        run: python panel/app.py
